// all info pulled from github
var user = {
	"id"                     : "4708",
	"github_id"              : "1206482",
	"login"                  : "AnthonyNeace",
	"name"                   : "Anthony Neace",
	"blog"                   : "http://www.swcity.net",
	"location"               : "Kentucky",
	"type"                   : "User",
	"created_at"             : "2011-11-19 14:18:09+00",
	"updated_at"             : "2016-02-27 01:08:31+00",
	"scope_public_repo"      : "0",
	"scope_user_email"       : "0",
	"created"                : "2016-01-30 20:40:38+00",
	"updated"                : "2016-02-29 21:45:35+00",
	"gh_data"                : {
	                           "gravatar_id" : "",
	                           "subscriptions_url" : "https://api.github.com/users/AnthonyNeace/subscriptions",
	                           "organizations_url" : "https://api.github.com/users/AnthonyNeace/orgs",
	                           "email" : null,
	                           "gists_url" : "https://api.github.com/users/AnthonyNeace/gists{/gist_id}",
	                           "followers_url" : "https://api.github.com/users/AnthonyNeace/followers",
	                           "created_at" : "2011-11-19T14:18:09Z",
	                           "site_admin" : false,
	                           "following_url" : "https://api.github.com/users/AnthonyNeace/following{/other_user}",
	                           "url" : "https://api.github.com/users/AnthonyNeace",
	                           "id" : 1206482,
	                           "public_gists" : 5,
	                           "company" : null,
	                           "bio" : null,
	                           "following" : 6,
	                           "followers" : 6,
	                           "starred_url" : "https://api.github.com/users/AnthonyNeace/starred{/owner}{/repo}",
	                           "location" : "Kentucky",
	                           "avatar_url" : "https://avatars.githubusercontent.com/u/1206482?v=3",
	                           "name" : "Anthony Neace",
	                           "repos_url" : "https://api.github.com/users/AnthonyNeace/repos",
	                           "blog" : "http://www.swcity.net",
	                           "login" : "AnthonyNeace",
	                           "updated_at" : "2016-02-27T01:08:31Z",
	                           "html_url" : "https://github.com/AnthonyNeace",
	                           "type" : "User",
	                           "received_events_url" : "https://api.github.com/users/AnthonyNeace/received_events",
	                           "events_url" : "https://api.github.com/users/AnthonyNeace/events{/privacy}",
	                           "hireable" : null,
	                           "public_repos" : 17
	                        },
	"isa_owners_team_member" : "0",
	"instant_answers": [
		{
			"id"                    : "aws_ec2_cheat_sheet",
			"name"                  : "AWS EC2 Cheat Sheet",
			"description"           : "The AWS EC2 Cheat Sheet lists EC2 resources and groups referential information that is otherwise buried in documentation.",
			"perl_module"           : "DDG::Goodie::CheatSheets",
			"dev_milestone"         : "complete",
			"repo"                  : "goodies",
			"code"                  : ["share/goodie/cheat_sheets/json/aws-ec2.json"],
			"src_url"               : "http://aws.amazon.com/documentation/ec2/",
			"example_query"         : "aws ec2 cheat sheet",
			"other_queries"         : ["ec2 cheat sheet"],
			"tab"                   : "Cheat Sheet",
			"producer"              : "Moollaza",
			"developer"             : [{"url":"https://github.com/AnthonyNeace","name":"AnthonyNeace","type":"github"}],
			"browsers_chrome"       : "1",
			"meta_id"               : "aws_ec2_cheat_sheet",
			"created_date"          : "2016-02-21",
			"last_commit"           : {"admin":0,"duckco":null,"issue_id":2410,"date":"2016-03-01T23:53:28Z","comleader":0,"message":"Renaming file to match correct convention.","diff":"https://github.com/duckduckgo/zeroclickinfo-goodies/commit/fe73d6b28ab52cc1f18d04f6d2b8c7ab7a9e91da","user":"aneace"},
			"last_comment"          : {"admin":1,"duckco":"Moollaza","text":"Thanks! This LGTM :+1:","date":"2016-03-02T19:33:21Z","comleader":0,"user":"moollaza","id":191389297},
			"last_update"           : "2016-03-02T19:33:35Z",
			"updated"               : "2016-03-03 02:35:21+00",
			"all_comments"          : [{"admin":0,"duckco":null,"text":"\n## [AWS EC2 Cheat Sheet](https://duck.co/ia/view/aws_ec2_cheat_sheet)\n\n**Description**: The AWS EC2 Cheat Sheet lists EC2 resources and groups referential information that is otherwise buried in documentation.\n\n**Example Query**: [aws ec2 cheat sheet](https://beta.duckduckgo.com/?q=aws ec2 cheat sheet), [ec2 cheat sheet](https://beta.duckduckgo.com/?q=ec2 cheat sheet)\n\n**Tab Name**: Cheat Sheet\n\n**Source**: http://aws.amazon.com/documentation/ec2/\n\n*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/aws_ec2_cheat_sheet)*\n\n---\n*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/aws_ec2_cheat_sheet)*\n","date":"2016-02-21T06:03:06Z","comleader":0,"user":"daxtheduck","id":186754643},{"admin":0,"duckco":"HyperAnthony","text":"Quick progress review:\r\n\r\nI compiled the current categories from AWS documentation with an intent to gather information that is likely to be searched often, is not immediately obvious for an inexperienced user, and/or would be commonly referenced by an experienced user.\r\n\r\nUsing [StackOverFlow](http://stackoverflow.com/questions/tagged/amazon-ec2?sort=votes&pageSize=50) and [ServerFault](http://serverfault.com/questions/tagged/amazon-ec2?sort=votes&pageSize=15) [Amazon-EC2] tagged questions sorted by vote as a source, I think there is strong justification for these categories:\r\n\r\n* Glossary/Terminology: Questions about basic behavior of EC2 resources like using key pairs, how security groups work, why an instance wouldn't have public DNS, etc... litter the highly upvoted lists\r\n* Instance Metadata Service and Categories: Questions like 'How do I find out `<instance metadata>` from within EC2?' are highly upvoted, and querying the instance metadata service is always the answer.\r\n* Instance Lifecycle States: Many questions about operations that must be done when an instance is in a particular state, can highlight that here.\r\n* CloudWatch Metrics: Many questions that could be resolved with monitoring.\r\n\r\nCategories that are harder to justify based on data available, but are likely still useful and commonly searched:\r\n\r\n* Instance Types\r\n* Purchasing Options\r\n\r\nCategories I am considering removing:\r\n\r\n* Running Instance (Per-Region) Default Limits\r\n* Resource Default Limits\r\n\r\nI'd like to continue revising this sheet to make sure information is present to cover many of these common questions. I may need to add a 'Common Operations' category that very simply describes how to do things like setting up a keypair, changing a security group, etc.","date":"2016-02-22T14:39:47Z","comleader":0,"user":"AnthonyNeace","id":187209128},{"admin":1,"duckco":"Moollaza","text":"@AnthonyNeace please change the filename to `aws-ec2.json` we use dashes instead of underscores for the filenames :+1: ","date":"2016-03-01T17:00:08Z","comleader":0,"user":"moollaza","id":54598178},{"admin":1,"duckco":"Moollaza","text":"@AnthonyNeace thanks for the progress update! I really appreciate how much effort you've put into determining what the sections should be. I think what you have is a great start and ultimately we'll probably end up making changes once this is announced and we get some feedback.\r\n\r\nI've set this up to be deployed to beta for testing :+1: ","date":"2016-03-01T17:05:40Z","comleader":0,"user":"moollaza","id":190816840},{"admin":0,"duckco":null,"text":"Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=aws ec2 cheat sheet)\n                ![](https://ia-screenshots.s3.amazonaws.com/aws_ec2_cheat_sheet_index.png)\n                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/aws_ec2_cheat_sheet_mobile.png)","date":"2016-03-02T00:04:26Z","comleader":0,"user":"daxtheduck","id":190979353},{"admin":1,"duckco":"Moollaza","text":"Thanks! This LGTM :+1:","date":"2016-03-02T19:33:21Z","comleader":0,"user":"moollaza","id":191389297}],
			"release_version"       : "1121.000",
			"deployment_state"      : "released",
			"blockgroup"            : "goodie",
			"public"                : "1",
			"maintainer"            : {"duckco":"HyperAnthony","github":"AnthonyNeace"},
			"production_state"      : "offline"
		},
		{
			"id"                    : "powershell_cheat_sheet",
			"name"                  : "Microsoft Powershell Cheat Sheet",
			"description"           : "Cheat sheet for syntax, operators, and operations in the PowerShell language.",
			"perl_module"           : "DDG::Goodie::CheatSheets",
			"dev_milestone"         : "complete",
			"repo"                  : "goodies",
			"code"                  : ["share/goodie/cheat_sheets/json/powershell.json"],
			"src_url"               : "https://technet.microsoft.com/en-us/library/hh847856.aspx",
			"example_query"         : "powershell cheat sheet",
			"other_queries"         : [],
			"tab"                   : "Cheat Sheet",
			"producer"              : "Jag",
			"developer"             : [{"url":"https://github.com/AnthonyNeace","name":"AnthonyNeace","type":"github"}],
			"browsers_firefox"      : "1",
			"meta_id"               : "powershell_cheat_sheet",
			"created_date"          : "2016-01-31",
			"last_commit"           : {"admin":0,"duckco":null,"issue_id":2191,"date":"2016-02-18T02:17:36Z","comleader":0,"message":"Switching to terminal template from code template","diff":"https://github.com/duckduckgo/zeroclickinfo-goodies/commit/99fcf53377a4d0fa8481fed1eecba1eaa874a6b3","user":"aneace"},
			"last_comment"          : {"admin":1,"duckco":"Moollaza","text":"Hey @AnthonyNeace thanks again for creating the Powershell Cheat Sheet! You did a great job. We at DuckDuckGo, the DuckDuckHack community, and all the people who will encounter this Instant Answer really appreciate it.\r\n\r\nWe could really use your help on something else now: There was a nice suggestion about Improving the MD5 and Bas64 IA triggering in https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1074 and I think you'd similarly do a great job with it. Please comment on this issue if you'd be willing to take it up!\r\n\r\nI think it is a good fit for you, but I'm of course not entirely sure, so I'd love to chat if you're around this week or next. Please message me on slack (@moollaza) or send me an email (moollaza@duckduckgo.com) if you'd be interested in talking.\r\n\r\nThanks again!","date":"2016-03-01T17:33:05Z","comleader":0,"user":"moollaza","id":190825317},
			"last_update"           : "2016-03-08T20:57:19Z",
			"updated"               : "2016-03-08 21:03:37+00",
			"all_comments"          : [{"admin":0,"duckco":null,"text":"@AnthonyNeace Hey!\n        \nThanks for taking the time to contribute! We really appreciate it.\n\nWe work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:\n\n1. Pull Request is reviewed by the DuckDuckGo staff and community\n2. Staff and community will leave feedback with any necessary updates to the function or design.\n3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!\n\nWhile the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put \"Dev Merch\" in the subject line:\n\nName:\nStreet Address:\nCity:\nState / Province:\nCountry:\nPhone (Non-US Orders only): \nT-shirt size:\nGitHub username:\nLink to this Pull Request:\n\nIf you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.\n\n>More Info: https://duck.co/duckduckhack/submission_and_review\n\nThanks!","date":"2016-02-01T04:53:08Z","comleader":0,"user":"daxtheduck","id":177763528},{"admin":0,"duckco":null,"text":"\n## [Microsoft Powershell Cheat Sheet](https://duck.co/ia/view/powershell_cheat_sheet)\n\n**Description**: Cheat sheet for syntax, operators, and operations in the PowerShell language.\n\n**Example Query**: [powershell cheat sheet](https://beta.duckduckgo.com/?q=powershell cheat sheet)\n\n**Tab Name**: Cheat Sheet\n\n**Source**: https://technet.microsoft.com/en-us/library/hh847856.aspx\n\n*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/powershell_cheat_sheet)*\n\n---\n*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/powershell_cheat_sheet)*\n","date":"2016-02-01T04:53:08Z","comleader":0,"user":"daxtheduck","id":177763532},{"admin":0,"duckco":null,"text":"Hey @AnthonyNeace Welcome to duckduckhack :smile: ","date":"2016-02-01T05:21:15Z","comleader":0,"user":"gautamkrishnar","id":177770366},{"admin":0,"duckco":"mintsoft","text":"Can you change the key to:\r\n`\"key\": \"\\\"MyString\\\" -match \\\"^String$\\\"\"` so it's more obvious that it's regex?","date":"2016-02-01T12:49:20Z","comleader":0,"user":"mintsoft","id":51413979},{"admin":0,"duckco":"mintsoft","text":"Hmm, I wonder if we can rephrase this as \"Returns true if the right argument is in the present in the array (left)\" or similar?","date":"2016-02-01T12:50:26Z","comleader":0,"user":"mintsoft","id":51414081},{"admin":0,"duckco":"mintsoft","text":"Can we change this to `DateTime`; I appreciate that Powershell is case insensitive however I think it's better if the names are accurate to the .NET framework","date":"2016-02-01T12:52:05Z","comleader":0,"user":"mintsoft","id":51414250},{"admin":0,"duckco":"mintsoft","text":"Alternative to this is `$arr = @(1)` which looks a little cleaner, however I think we should keep the floating `,` in here too as people do use it","date":"2016-02-01T12:54:42Z","comleader":0,"user":"mintsoft","id":51414466},{"admin":0,"duckco":"HyperAnthony","text":"@gautamkrishnar Thanks!\r\n\r\n@mintsoft Thanks for the feedback, implemented it in the latest commit.","date":"2016-02-01T16:53:54Z","comleader":0,"user":"AnthonyNeace","id":178065146},{"admin":1,"duckco":"Moollaza","text":"@AnthonyNeace let's use the `terminal` template -- this will look much better!","date":"2016-02-18T01:53:17Z","comleader":0,"user":"moollaza","id":53262180},{"admin":0,"duckco":null,"text":"Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=powershell cheat sheet)\n                ![](https://ia-screenshots.s3.amazonaws.com/powershell_cheat_sheet_index.png)\n                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/powershell_cheat_sheet_mobile.png)","date":"2016-02-18T02:26:34Z","comleader":0,"user":"daxtheduck","id":185512304},{"admin":1,"duckco":"Moollaza","text":"@AnthonyNeace Thanks! This LGTM :+1:","date":"2016-02-18T02:36:08Z","comleader":0,"user":"moollaza","id":185514773},{"admin":1,"duckco":"Moollaza","text":"Hey @AnthonyNeace thanks again for creating the Powershell Cheat Sheet! You did a great job. We at DuckDuckGo, the DuckDuckHack community, and all the people who will encounter this Instant Answer really appreciate it.\r\n\r\nWe could really use your help on something else now: There was a nice suggestion about Improving the MD5 and Bas64 IA triggering in https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1074 and I think you'd similarly do a great job with it. Please comment on this issue if you'd be willing to take it up!\r\n\r\nI think it is a good fit for you, but I'm of course not entirely sure, so I'd love to chat if you're around this week or next. Please message me on slack (@moollaza) or send me an email (moollaza@duckduckgo.com) if you'd be interested in talking.\r\n\r\nThanks again!","date":"2016-03-01T17:33:05Z","comleader":0,"user":"moollaza","id":190825317}],
			"at_mentions"           : [{"name":"HyperAnthony"},{"name":"Moollaza"}],
			"release_version"       : "1120.000",
			"deployment_state"      : "released",
			"blockgroup"            : "goodie",
			"public"                : "1",
			"maintainer"            : {"duckco":"HyperAnthony","github":"AnthonyNeace"},
			"production_state"      : "offline"
		},
		{
			"id"                    : "activeworlds_cheat_sheet",
			"name"                  : "Activeworlds Cheat Sheet",
			"description"           : "Keyboard shortcuts for ActiveWorlds, a virtual worlds software.",
			"perl_module"           : "DDG::Goodie::CheatSheets",
			"dev_milestone"         : "complete",
			"repo"                  : "goodies",
			"code"                  : ["share/goodie/cheat_sheets/json/activeworlds.json"],
			"src_url"               : "http://awbuilder.blogspot.com/2016/01/reference-activeworlds-keyboard-defaults.html",
			"example_query"         : "activeworlds cheat sheet",
			"other_queries"         : ["activeworlds help"],
			"tab"                   : "Cheat Sheet",
			"producer"              : "Moollaza",
			"perl_dependencies"     : [],
			"developer"             : [{"url":"https://github.com/AnthonyNeace","name":"AnthonyNeace","type":"github"}],
			"meta_id"               : "activeworlds_cheat_sheet",
			"dev_date"              : "2016-03-01",
			"created_date"          : "2016-01-30",
			"last_commit"           : {"admin":0,"duckco":null,"issue_id":2200,"date":"2016-03-01T23:59:17Z","comleader":0,"message":"Fixing arrow key values that were lost in previous commits.","diff":"https://github.com/duckduckgo/zeroclickinfo-goodies/commit/49ec96455622073dd16b8385279554a1d01d97a9","user":"aneace"},
			"last_comment"          : {"admin":1,"duckco":"Moollaza","text":"@AnthonyNeace Thanks! This LGTM :+1:","date":"2016-03-02T19:34:16Z","comleader":0,"user":"moollaza","id":191389807},
			"last_update"           : "2016-03-08T20:56:37Z",
			"updated"               : "2016-03-08 21:03:36+00",
			"all_comments"          : [{"admin":0,"duckco":null,"text":"@AnthonyNeace Hey!\n        \nThanks for taking the time to contribute! We really appreciate it.\n\nWe work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:\n\n1. Pull Request is reviewed by the DuckDuckGo staff and community\n2. Staff and community will leave feedback with any necessary updates to the function or design.\n3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!\n\nWhile the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put \"Dev Merch\" in the subject line:\n\nName:\nStreet Address:\nCity:\nState / Province:\nCountry:\nPhone (Non-US Orders only): \nT-shirt size:\nGitHub username:\nLink to this Pull Request:\n\nIf you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.\n\n>More Info: https://duck.co/duckduckhack/submission_and_review\n\nThanks!","date":"2016-02-02T01:37:24Z","comleader":0,"user":"daxtheduck","id":178299275},{"admin":0,"duckco":null,"text":"\n## [Activeworlds Cheat Sheet](https://duck.co/ia/view/activeworlds_cheat_sheet)\n\n**Description**: Keyboard shortcuts for ActiveWorlds, a virtual worlds software.\n\n**Example Query**: [activeworlds cheat sheet](https://beta.duckduckgo.com/?q=activeworlds cheat sheet), [activeworlds help](https://beta.duckduckgo.com/?q=activeworlds help)\n\n**Tab Name**: Cheat Sheet\n\n**Source**: http://awbuilder.blogspot.com/2016/01/reference-activeworlds-keyboard-defaults.html\n\n*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/activeworlds_cheat_sheet)*\n\n---\n*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/activeworlds_cheat_sheet)*\n","date":"2016-02-02T01:37:24Z","comleader":0,"user":"daxtheduck","id":178299277},{"admin":1,"duckco":"Moollaza","text":"Do the `?` mean you're not sure what the key is? If not, let's just use `Numpad X`","date":"2016-03-01T17:45:18Z","comleader":0,"user":"moollaza","id":54604687},{"admin":1,"duckco":"Moollaza","text":"Likewise anything unknown we should remove. We can announce this once it's live an I'm sure we'll get feedback\r\nWe can even ask people to help add anything missing","date":"2016-03-01T17:46:03Z","comleader":0,"user":"moollaza","id":54604995},{"admin":1,"duckco":"Moollaza","text":"Actually, now that it's on Beta -- we could ask for help now if you'd like\r\n\r\n/cc @tagawa ","date":"2016-03-01T17:46:55Z","comleader":0,"user":"moollaza","id":54605125},{"admin":0,"duckco":"HyperAnthony","text":"@moollaza Whoops, those should be arrows. Think I goofed up the file encoding somehow when I closed the old pull request and the arrow characters got lost. Easy fix, I'll update it tonight. Thanks for the catch!","date":"2016-03-01T19:00:25Z","comleader":0,"user":"AnthonyNeace","id":190852679},{"admin":0,"duckco":null,"text":"Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=activeworlds cheat sheet)\n                ![](https://ia-screenshots.s3.amazonaws.com/activeworlds_cheat_sheet_index.png)\n                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/activeworlds_cheat_sheet_mobile.png)","date":"2016-03-02T00:15:05Z","comleader":0,"user":"daxtheduck","id":190983961},{"admin":1,"duckco":"Moollaza","text":"@AnthonyNeace Thanks! This LGTM :+1:","date":"2016-03-02T19:34:16Z","comleader":0,"user":"moollaza","id":191389807}],
			"at_mentions"           : [{"name":"HyperAnthony"}],
			"release_version"       : "1121.000",
			"deployment_state"      : "released",
			"blockgroup"            : "goodie",
			"public"                : "1",
			"maintainer"            : {"duckco":"HyperAnthony","github":"AnthonyNeace"},
			"production_state"      : "offline"
		}
	],
	"issues": [
		{
			"id"                      : "5156",
			"github_id"               : "135164188",
			"github_repo_id"          : "3",
			"github_user_id"          : "4708",
			"number"                  : "2410",
			"comments"                : "5",
			"title"                   : "New AWS EC2 Cheat Sheet",
			"body"                    : "New AWS EC2 Cheat Sheet, work in progress. Interested in demystifying many of the resources and exposing information that is otherwise buried deep in docs.  I think I might be trying to stuff too much in a single sheet, any opinions/feedback on that (or even more content to add!) would be appreciated.\r \r Related conversation at https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2277\r \r IA: https://duck.co/ia/view/aws_ec2_cheat_sheet",
			"state"                   : "closed",
			"created_at"              : "2016-02-21 05:44:29+00",
			"updated_at"              : "2016-03-02 19:33:35+00",
			"closed_at"               : "2016-03-02 19:33:35+00",
			"github_user_id_assignee" : "2344",
			"created"                 : "2016-02-21 05:45:56+00",
			"updated"                 : "2016-03-02 21:47:38+00",
			"gh_data"                 : {
			                            "closed_at" : "2016-03-02T19:33:35Z",
			                            "number" : 2410,
			                            "comments_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2410/comments",
			                            "labels_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2410/labels{/name}",
			                            "comments" : 5,
			                            "pull_request" : {
			                               "patch_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2410.patch",
			                               "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2410",
			                               "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/pulls/2410",
			                               "diff_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2410.diff"
			                            },
			                            "state" : "closed",
			                            "body" : "New AWS EC2 Cheat Sheet, work in progress. Interested in demystifying many of the resources and exposing information that is otherwise buried deep in docs.  I think I might be trying to stuff too much in a single sheet, any opinions/feedback on that (or even more content to add!) would be appreciated.\r\n\r\nRelated conversation at https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2277\r\n\r\nIA: https://duck.co/ia/view/aws_ec2_cheat_sheet",
			                            "created_at" : "2016-02-21T05:44:29Z",
			                            "assignee" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/moollaza/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/moollaza/orgs",
			                               "gists_url" : "https://api.github.com/users/moollaza/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/moollaza/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/moollaza/following{/other_user}",
			                               "url" : "https://api.github.com/users/moollaza",
			                               "id" : 873785,
			                               "starred_url" : "https://api.github.com/users/moollaza/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/873785?v=3",
			                               "repos_url" : "https://api.github.com/users/moollaza/repos",
			                               "login" : "moollaza",
			                               "html_url" : "https://github.com/moollaza",
			                               "events_url" : "https://api.github.com/users/moollaza/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/moollaza/received_events",
			                               "type" : "User"
			                            },
			                            "user" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/AnthonyNeace/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/AnthonyNeace/orgs",
			                               "gists_url" : "https://api.github.com/users/AnthonyNeace/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/AnthonyNeace/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/AnthonyNeace/following{/other_user}",
			                               "url" : "https://api.github.com/users/AnthonyNeace",
			                               "id" : 1206482,
			                               "starred_url" : "https://api.github.com/users/AnthonyNeace/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/1206482?v=3",
			                               "repos_url" : "https://api.github.com/users/AnthonyNeace/repos",
			                               "login" : "AnthonyNeace",
			                               "html_url" : "https://github.com/AnthonyNeace",
			                               "events_url" : "https://api.github.com/users/AnthonyNeace/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/AnthonyNeace/received_events",
			                               "type" : "User"
			                            },
			                            "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2410",
			                            "id" : 135164188,
			                            "labels" : [
			                               {
			                                  "color" : "006b75",
			                                  "name" : "CheatSheet",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/CheatSheet"
			                               },
			                               {
			                                  "color" : "02d7e1",
			                                  "name" : "New Instant Answer",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/New%20Instant%20Answer"
			                               }
			                            ],
			                            "locked" : false,
			                            "repository_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies",
			                            "updated_at" : "2016-03-02T19:33:35Z",
			                            "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2410",
			                            "milestone" : null,
			                            "events_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2410/events",
			                            "title" : "New AWS EC2 Cheat Sheet"
			                         },
			isa_pull_request        : 1
		},
		{
			"id"                      : "4884",
			"github_id"               : "130541276",
			"github_repo_id"          : "3",
			"github_user_id"          : "4708",
			"number"                  : "2200",
			"comments"                : "5",
			"title"                   : "New ActiveWorlds Cheat Sheet",
			"body"                    : "IA: https://duck.co/ia/view/activeworlds_cheat_sheet",
			"state"                   : "closed",
			"created_at"              : "2016-02-02 01:37:22+00",
			"updated_at"              : "2016-03-08 17:02:25+00",
			"closed_at"               : "2016-03-02 19:34:18+00",
			"github_user_id_assignee" : "2344",
			"created"                 : "2016-02-02 01:45:54+00",
			"updated"                 : "2016-03-08 17:47:49+00",
			"gh_data"                 : {
			                            "closed_at" : "2016-03-02T19:34:18Z",
			                            "number" : 2200,
			                            "comments_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2200/comments",
			                            "labels_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2200/labels{/name}",
			                            "comments" : 5,
			                            "pull_request" : {
			                               "patch_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2200.patch",
			                               "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2200",
			                               "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/pulls/2200",
			                               "diff_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2200.diff"
			                            },
			                            "state" : "closed",
			                            "body" : "IA: https://duck.co/ia/view/activeworlds_cheat_sheet",
			                            "created_at" : "2016-02-02T01:37:22Z",
			                            "assignee" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/moollaza/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/moollaza/orgs",
			                               "gists_url" : "https://api.github.com/users/moollaza/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/moollaza/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/moollaza/following{/other_user}",
			                               "url" : "https://api.github.com/users/moollaza",
			                               "id" : 873785,
			                               "starred_url" : "https://api.github.com/users/moollaza/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/873785?v=3",
			                               "repos_url" : "https://api.github.com/users/moollaza/repos",
			                               "login" : "moollaza",
			                               "html_url" : "https://github.com/moollaza",
			                               "events_url" : "https://api.github.com/users/moollaza/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/moollaza/received_events",
			                               "type" : "User"
			                            },
			                            "user" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/AnthonyNeace/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/AnthonyNeace/orgs",
			                               "gists_url" : "https://api.github.com/users/AnthonyNeace/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/AnthonyNeace/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/AnthonyNeace/following{/other_user}",
			                               "url" : "https://api.github.com/users/AnthonyNeace",
			                               "id" : 1206482,
			                               "starred_url" : "https://api.github.com/users/AnthonyNeace/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/1206482?v=3",
			                               "repos_url" : "https://api.github.com/users/AnthonyNeace/repos",
			                               "login" : "AnthonyNeace",
			                               "html_url" : "https://github.com/AnthonyNeace",
			                               "events_url" : "https://api.github.com/users/AnthonyNeace/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/AnthonyNeace/received_events",
			                               "type" : "User"
			                            },
			                            "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2200",
			                            "id" : 130541276,
			                            "labels" : [
			                               {
			                                  "color" : "006b75",
			                                  "name" : "CheatSheet",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/CheatSheet"
			                               },
			                               {
			                                  "color" : "02d7e1",
			                                  "name" : "New Instant Answer",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/New%20Instant%20Answer"
			                               }
			                            ],
			                            "locked" : false,
			                            "repository_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies",
			                            "updated_at" : "2016-03-08T17:02:25Z",
			                            "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2200",
			                            "milestone" : null,
			                            "events_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2200/events",
			                            "title" : "New ActiveWorlds Cheat Sheet"
			                         },
			"isa_pull_request"        : 1
		},
		{

			"id"                      : "4870",
			"github_id"               : "130255745",
			"github_repo_id"          : "3",
			"github_user_id"          : "4708",
			"number"                  : "2191",
			"comments"                : "7",
			"title"                   : "New PowerShell Cheat Sheet",
			"body"                    : "This is a cheat sheet for syntax and operators in the PowerShell language.  Most examples are from the language's builtin docs that can also be found [here](https://technet.microsoft.com/en-us/library/hh847856.aspx).\r \r IA: https://duck.co/ia/view/powershell_cheat_sheet",
			"state"                   : "closed",
			"created_at"              : "2016-02-01 04:53:04+00",
			"updated_at"              : "2016-03-08 17:02:26+00",
			"closed_at"               : "2016-02-18 02:36:11+00",
			"github_user_id_assignee" : "2397",
			"created"                 : "2016-02-01 05:45:53+00",
			"updated"                 : "2016-03-08 17:47:49+00",
			"gh_data"                 : {
			                            "closed_at" : "2016-02-18T02:36:11Z",
			                            "number" : 2191,
			                            "comments_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2191/comments",
			                            "labels_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2191/labels{/name}",
			                            "comments" : 7,
			                            "pull_request" : {
			                               "patch_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2191.patch",
			                               "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2191",
			                               "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/pulls/2191",
			                               "diff_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2191.diff"
			                            },
			                            "state" : "closed",
			                            "body" : "This is a cheat sheet for syntax and operators in the PowerShell language.  Most examples are from the language's builtin docs that can also be found [here](https://technet.microsoft.com/en-us/library/hh847856.aspx).\r\n\r\nIA: https://duck.co/ia/view/powershell_cheat_sheet",
			                            "created_at" : "2016-02-01T04:53:04Z",
			                            "assignee" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/mintsoft/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/mintsoft/orgs",
			                               "gists_url" : "https://api.github.com/users/mintsoft/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/mintsoft/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/mintsoft/following{/other_user}",
			                               "url" : "https://api.github.com/users/mintsoft",
			                               "id" : 978048,
			                               "starred_url" : "https://api.github.com/users/mintsoft/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/978048?v=3",
			                               "repos_url" : "https://api.github.com/users/mintsoft/repos",
			                               "login" : "mintsoft",
			                               "html_url" : "https://github.com/mintsoft",
			                               "events_url" : "https://api.github.com/users/mintsoft/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/mintsoft/received_events",
			                               "type" : "User"
			                            },
			                            "user" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/AnthonyNeace/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/AnthonyNeace/orgs",
			                               "gists_url" : "https://api.github.com/users/AnthonyNeace/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/AnthonyNeace/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/AnthonyNeace/following{/other_user}",
			                               "url" : "https://api.github.com/users/AnthonyNeace",
			                               "id" : 1206482,
			                               "starred_url" : "https://api.github.com/users/AnthonyNeace/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/1206482?v=3",
			                               "repos_url" : "https://api.github.com/users/AnthonyNeace/repos",
			                               "login" : "AnthonyNeace",
			                               "html_url" : "https://github.com/AnthonyNeace",
			                               "events_url" : "https://api.github.com/users/AnthonyNeace/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/AnthonyNeace/received_events",
			                               "type" : "User"
			                            },
			                            "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2191",
			                            "id" : 130255745,
			                            "labels" : [
			                               {
			                                  "color" : "006b75",
			                                  "name" : "CheatSheet",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/CheatSheet"
			                               },
			                               {
			                                  "color" : "02d7e1",
			                                  "name" : "New Instant Answer",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/New%20Instant%20Answer"
			                               }
			                            ],
			                            "locked" : false,
			                            "repository_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies",
			                            "updated_at" : "2016-03-08T17:02:26Z",
			                            "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2191",
			                            "milestone" : null,
			                            "events_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2191/events",
			                            "title" : "New PowerShell Cheat Sheet"
			                         },
			"isa_pull_request"        : 1
		},
		{
			"id"                      : "4848",
			"github_id"               : "130073579",
			"github_repo_id"          : "3",
			"github_user_id"          : "4708",
			"number"                  : "2175",
			"comments"                : "4",
			"title"                   : "New ActiveWorlds Cheat Sheet",
			"body"                    : "Closed, see here: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2200",
			"state"                   : "closed",
			"created_at"              : "2016-01-31 04:08:37+00",
			"updated_at"              : "2016-03-02 19:33:52+00",
			"closed_at"               : "2016-02-02 01:16:33+00",
			"created"                 : "2016-01-31 05:45:50+00",
			"updated"                 : "2016-03-02 21:47:38+00",
			"gh_data"                 : {
			                            "closed_at" : "2016-02-02T01:16:33Z",
			                            "number" : 2175,
			                            "comments_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2175/comments",
			                            "labels_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2175/labels{/name}",
			                            "comments" : 4,
			                            "pull_request" : {
			                               "patch_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2175.patch",
			                               "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2175",
			                               "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/pulls/2175",
			                               "diff_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2175.diff"
			                            },
			                            "state" : "closed",
			                            "body" : "Closed, see here: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2200",
			                            "created_at" : "2016-01-31T04:08:37Z",
			                            "assignee" : null,
			                            "user" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/AnthonyNeace/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/AnthonyNeace/orgs",
			                               "gists_url" : "https://api.github.com/users/AnthonyNeace/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/AnthonyNeace/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/AnthonyNeace/following{/other_user}",
			                               "url" : "https://api.github.com/users/AnthonyNeace",
			                               "id" : 1206482,
			                               "starred_url" : "https://api.github.com/users/AnthonyNeace/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/1206482?v=3",
			                               "repos_url" : "https://api.github.com/users/AnthonyNeace/repos",
			                               "login" : "AnthonyNeace",
			                               "html_url" : "https://github.com/AnthonyNeace",
			                               "events_url" : "https://api.github.com/users/AnthonyNeace/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/AnthonyNeace/received_events",
			                               "type" : "User"
			                            },
			                            "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2175",
			                            "id" : 130073579,
			                            "labels" : [
			                               {
			                                  "color" : "006b75",
			                                  "name" : "CheatSheet",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/CheatSheet"
			                               },
			                               {
			                                  "color" : "02d7e1",
			                                  "name" : "New Instant Answer",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/New%20Instant%20Answer"
			                               }
			                            ],
			                            "locked" : false,
			                            "repository_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies",
			                            "updated_at" : "2016-03-02T19:33:52Z",
			                            "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2175",
			                            "milestone" : null,
			                            "events_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2175/events",
			                            "title" : "New ActiveWorlds Cheat Sheet"
			                         },
			"isa_pull_request"        : 1
		}
	]
};

