// all info pulled from github
var user = {
	"id"                     : "4379",
	"github_id"              : "8598426",
	"login"                  : "GuiltyDolphin",
	"name"                   : "Ben Moon",
	"email"                  : "guiltydolphin@gmail.com",
	"type"                   : "User",
	"created_at"             : "2014-08-30 11:49:55+00",
	"updated_at"             : "2016-02-27 18:47:15+00",
	"scope_public_repo"      : "0",
	"scope_user_email"       : "0",
	"created"                : "2015-12-06 13:46:20+00",
	"updated"                : "2016-03-08 16:11:38+00",
	"gh_data"                : {
	                           "gravatar_id" : "",
	                           "subscriptions_url" : "https://api.github.com/users/GuiltyDolphin/subscriptions",
	                           "organizations_url" : "https://api.github.com/users/GuiltyDolphin/orgs",
	                           "email" : "guiltydolphin@gmail.com",
	                           "gists_url" : "https://api.github.com/users/GuiltyDolphin/gists{/gist_id}",
	                           "followers_url" : "https://api.github.com/users/GuiltyDolphin/followers",
	                           "created_at" : "2014-08-30T11:49:55Z",
	                           "site_admin" : false,
	                           "following_url" : "https://api.github.com/users/GuiltyDolphin/following{/other_user}",
	                           "url" : "https://api.github.com/users/GuiltyDolphin",
	                           "id" : 8598426,
	                           "public_gists" : 5,
	                           "company" : null,
	                           "bio" : null,
	                           "following" : 0,
	                           "followers" : 14,
	                           "starred_url" : "https://api.github.com/users/GuiltyDolphin/starred{/owner}{/repo}",
	                           "location" : null,
	                           "avatar_url" : "https://avatars.githubusercontent.com/u/8598426?v=3",
	                           "name" : "Ben Moon",
	                           "repos_url" : "https://api.github.com/users/GuiltyDolphin/repos",
	                           "blog" : null,
	                           "login" : "GuiltyDolphin",
	                           "updated_at" : "2016-02-27T18:47:15Z",
	                           "html_url" : "https://github.com/GuiltyDolphin",
	                           "type" : "User",
	                           "received_events_url" : "https://api.github.com/users/GuiltyDolphin/received_events",
	                           "events_url" : "https://api.github.com/users/GuiltyDolphin/events{/privacy}",
	                           "hireable" : null,
	                           "public_repos" : 22
	                        },
	"isa_owners_team_member" : "0",
	"instant_answers": [
		{
			"id"                    : "timergoodie",
			"name"                  : "Timergoodie",
			"dev_milestone"         : "planning",
			"repo"                  : "goodies",
			"developer"             : [{"name":"GuiltyDolphin","url":"https://duck.co/user/GuiltyDolphin","type":"duck.co"}],
			"meta_id"               : "timergoodie",
			"created_date"          : "2016-03-03",
			"updated"               : "2016-03-03 19:57:04+00",
			"public"                : "0",
			"maintainer"            : {"duckco":"GuiltyDolphin","github":"GuiltyDolphin"},
			"production_state"      : "offline"
		},
		{
			"id"                    : "kana",
			"name"                  : "Kana",
			"description"           : "Convert katakana, hiragana or romaji texts between each other",
			"perl_module"           : "DDG::Goodie::Kana",
			"dev_milestone"         : "live",
			"status"                : "qa",
			"repo"                  : "goodies",
			"code"                  : ["lib/DDG/Goodie/Kana.pm"],
			"example_query"         : "カひらがなタカナ romaji",
			"tab"                   : "Answer",
			"unsafe"                : "0",
			"producer"              : "Jag",
			"perl_dependencies"     : ["Lingua::JA::Moji"],
			"triggers"              : ["hiragana","katakana","romaji"],
			"designer"              : "abeyang",
			"developer"             : [{"name":"hradecek","url":"https://duck.co/user/hradecek"},{"url":"https://github.com/GuiltyDolphin","name":"GuiltyDolphin","type":"github"}],
			"test_machine"          : "ddh9",
			"meta_id"               : "kana",
			"created_date"          : "2016-02-26",
			"last_commit"           : {"admin":0,"duckco":null,"issue_id":2628,"date":"2016-02-26T20:52:14Z","comleader":0,"message":"Silence Kana warning\n\nFixes #2380","diff":"https://github.com/duckduckgo/zeroclickinfo-goodies/commit/7cfb9562676fdcbe6d46a0cd0efa0d6021124257","user":"Ben Moon"},
			"last_comment"          : {"admin":1,"duckco":"Moollaza","text":"Thanks! This LGTM :+1:","date":"2016-02-26T22:00:42Z","comleader":0,"user":"moollaza","id":189501645},
			"last_update"           : "2016-02-27T09:37:42Z",
			"updated"               : "2016-03-03 02:35:21+00",
			"all_comments"          : [{"admin":0,"duckco":null,"text":"\n## [Kana](https://duck.co/ia/view/kana)\n\n**Description**: Convert katakana, hiragana or romaji texts between each other\n\n**Example Query**: [カひらがなタカナ romaji](https://beta.duckduckgo.com/?q=カひらがなタカナ romaji)\n\n**Tab Name**: Answer\n\n**Source**:  \n\n*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/kana)*\n\n---\n*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/kana)*\n","date":"2016-02-26T20:54:52Z","comleader":0,"user":"daxtheduck","id":189479982},{"admin":1,"duckco":"Moollaza","text":"Thanks! This LGTM :+1:","date":"2016-02-26T22:00:42Z","comleader":0,"user":"moollaza","id":189501645}],
			"release_version"       : "1121.000",
			"deployment_state"      : "live",
			"blockgroup"            : "goodie",
			"public"                : "1",
			"production_state"      : "online"
		},
		{
			"id"                    : "markdown_reference",
			"name"                  : "Markdown Reference",
			"description"           : "Reference for various Markdown elements.",
			"perl_module"           : "DDG::Goodie::MarkdownReference",
			"dev_milestone"         : "testing",
			"repo"                  : "goodies",
			"src_url"               : "https://daringfireball.net/projects/markdown/syntax",
			"example_query"         : "markdown headers",
			"other_queries"         : [],
			"tab"                   : "Answer",
			"producer"              : "Moollaza",
			"triggers"              : ["markdown","md"],
			"developer"             : [{"name":"GuiltyDolphin","url":"https://duck.co/user/GuiltyDolphin","type":"duck.co"}],
			"meta_id"               : "markdown_reference",
			"created_date"          : "2016-02-06",
			"last_commit"           : {"admin":0,"duckco":null,"issue_id":2241,"date":"2016-02-06T13:54:41Z","comleader":0,"message":"Move synonyms into JSON file","diff":"https://github.com/duckduckgo/zeroclickinfo-goodies/commit/5ef7d7b74b4b0557935bf43a452d2a4593dafd86","user":"Ben Moon"},
			"last_comment"          : {"admin":0,"duckco":null,"text":"\n## [Markdown Reference](https://duck.co/ia/view/markdown_reference)\n\n**Description**: Reference for various Markdown elements.\n\n**Example Query**: [markdown headers](https://beta.duckduckgo.com/?q=markdown headers), [](https://beta.duckduckgo.com/?q=)\n\n**Tab Name**: Answer\n\n**Source**: https://daringfireball.net/projects/markdown/syntax\n\n*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/markdown_reference)*\n\n---\n*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/markdown_reference)*\n","date":"2016-02-06T13:29:13Z","comleader":0,"user":"daxtheduck","id":180765272},
			"last_update"           : "2016-02-13T13:00:08Z",
			"updated"               : "2016-03-08 15:48:10+00",
			"all_comments"          : [{"admin":0,"duckco":null,"text":"\n## [Markdown Reference](https://duck.co/ia/view/markdown_reference)\n\n**Description**: Reference for various Markdown elements.\n\n**Example Query**: [markdown headers](https://beta.duckduckgo.com/?q=markdown headers), [](https://beta.duckduckgo.com/?q=)\n\n**Tab Name**: Answer\n\n**Source**: https://daringfireball.net/projects/markdown/syntax\n\n*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/markdown_reference)*\n\n---\n*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/markdown_reference)*\n","date":"2016-02-06T13:29:13Z","comleader":0,"user":"daxtheduck","id":180765272}],
			"blockgroup"            : "goodie",
			"public"                : "1",
			"maintainer"            : {"duckco":"GuiltyDolphin","github":"GuiltyDolphin"},
			"production_state"      : "offline"
		},
		{
			"id"                    : "markdownreference",
			"name"                  : "Markdownreference",
			"description"           : "Provides a reference for common markdown syntax.",
			"dev_milestone"         : "planning",
			"repo"                  : "goodies",
			"src_url"               : "https://daringfireball.net/projects/markdown/syntax",
			"example_query"         : "markdown headers",
			"other_queries"         : [],
			"developer"             : [{"name":"GuiltyDolphin","url":"https://duck.co/user/GuiltyDolphin","type":"duck.co"}],
			"meta_id"               : "markdownreference",
			"created_date"          : "2016-02-06",
			"updated"               : "2016-02-29 21:30:06+00",
			"public"                : "0",
			"maintainer"            : {"duckco":"GuiltyDolphin","github":"GuiltyDolphin"},
			"production_state"      : "offline"
		},
		{
			"id"                    : "cheat_sheets",
			"name"                  : "Cheat Sheets (Controller)",
			"description"           : "The base controller for all Cheat Sheet Goodies. This is the actual Instant Answer that gets triggered, and decides which Cheat Sheet to display based on the query. This Goodie also handles the parsing of each Cheat Sheet's JSON and the display of the Cheat Sheet.",
			"perl_module"           : "DDG::Goodie::CheatSheets",
			"dev_milestone"         : "live",
			"status"                : "live",
			"repo"                  : "goodies",
			"code"                  : ["share/goodie/cheat_sheets/json/sql.json","share/goodie/cheat_sheets/triggers.yaml","t/CheatSheets/CheatSheetsJSON.t"],
			"example_query"         : "vim cheatsheet",
			"other_queries"         : [],
			"tab"                   : "Cheat Sheet",
			"producer"              : "Moollaza",
			"triggers"              : ["cheat sheet"],
			"developer"             : [{"url":"https://duck.co/user/zt","name":"zt","type":"duck.co"},{"url":"https://duck.co/user/alohaas","name":"alohaas","type":"duck.co"},{"url":"https://duck.co/user/Moollaza","name":"Moollaza","type":"duck.co"},{"url":"https://github.com/GuiltyDolphin","name":"GuiltyDolphin","type":"github"}],
			"code_review"           : "0",
			"design_review"         : "0",
			"meta_id"               : "cheat_sheets",
			"created_date"          : "2016-01-30",
			"last_commit"           : {"admin":0,"duckco":null,"issue_id":2333,"date":"2016-03-08T16:35:34Z","comleader":0,"message":"Update CheatSheetsJSON to use JSON::MaybeXS","diff":"https://github.com/duckduckgo/zeroclickinfo-goodies/commit/509f94af2c14ddc4fdd65150430e4a3782eb0639","user":"Ben Moon"},
			"last_comment"          : {"admin":0,"duckco":"GuiltyDolphin","text":"@moollaza That should be all of them!","date":"2016-03-08T16:37:35Z","comleader":0,"user":"GuiltyDolphin","id":193853666},
			"last_update"           : "2016-03-08T16:52:00Z",
			"updated"               : "2016-03-08 17:02:14+00",
			"all_comments"          : [{"admin":0,"duckco":null,"text":"\n## [Cheat Sheets (Controller)](https://duck.co/ia/view/cheat_sheets)\n\n**Description**: The base controller for all Cheat Sheet Goodies. This is the actual Instant Answer that gets triggered, and decides which Cheat Sheet to display based on the query. This Goodie also handles the parsing of each Cheat Sheet's JSON and the display of the Cheat Sheet.\n\n**Example Query**: [vim cheatsheet](https://beta.duckduckgo.com/?q=vim cheatsheet)\n\n**Tab Name**: Cheat Sheet\n\n**Source**:  \n\n*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/cheat_sheets)*\n\n---\n*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/cheat_sheets)*\n","date":"2016-02-18T13:03:57Z","comleader":0,"user":"daxtheduck","id":185710344},{"admin":1,"duckco":"Moollaza","text":"@GuiltyDolphin AFAIK JSON uses JSON::XS when available, so this shouldn't be necessary...\r\n\r\nCan you double check on that?\r\n","date":"2016-02-18T14:59:41Z","comleader":0,"user":"moollaza","id":185757021},{"admin":0,"duckco":"GuiltyDolphin","text":"@moollaza It uses `JSON::XS` when it can, but falls back to `JSON::PP` if that fails, if we're always going to be using `JSON::XS` though it kindah feels like we're introducing another step.\r\n\r\nYour call (but I think we should either always use `JSON::XS` or always use `JSON`).","date":"2016-02-18T15:29:49Z","comleader":0,"user":"GuiltyDolphin","id":185775144},{"admin":0,"duckco":"GuiltyDolphin","text":"@moollaza *Maybe* this?","date":"2016-02-18T18:58:21Z","comleader":0,"user":"GuiltyDolphin","id":185859733},{"admin":1,"duckco":"Moollaza","text":"Deploying to beta...","date":"2016-02-23T21:39:27Z","comleader":0,"user":"moollaza","id":187925359},{"admin":0,"duckco":"GuiltyDolphin","text":"@moollaza That should be all of them!","date":"2016-03-08T16:37:35Z","comleader":0,"user":"GuiltyDolphin","id":193853666}],
			"at_mentions"           : [{"name":"Moollaza"}],
			"release_version"       : "1121.000",
			"deployment_state"      : "live",
			"blockgroup"            : "goodie",
			"public"                : "1",
			"production_state"      : "online"
		}
	],
	"issues": [
		{
			"id"                      : "5525",
			"github_id"               : "139058174",
			"github_repo_id"          : "3",
			"github_user_id"          : "4379",
			"number"                  : "2714",
			"comments"                : "1",
			"title"                   : "DateMath: Expand Triggers",
			"body"                    : "Add a bunch more common forms that I've seen in the searches - also\r supports a couple of forms that should've been supported before.\r \r Things like `What day will it be in 120 days?`, `What time was it 3 hours ago?` etc...\r \r ---\r IA Page: https://duck.co/ia/view/date_math",
			"state"                   : "open",
			"created_at"              : "2016-03-07 18:44:59+00",
			"updated_at"              : "2016-03-07 21:37:21+00",
			"github_user_id_assignee" : "2397",
			"created"                 : "2016-03-07 21:47:42+00",
			"updated"                 : "2016-03-07 21:47:42+00",
			"gh_data"                 : {
			                            "closed_at" : null,
			                            "number" : 2714,
			                            "comments_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2714/comments",
			                            "labels_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2714/labels{/name}",
			                            "comments" : 1,
			                            "pull_request" : {
			                               "patch_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2714.patch",
			                               "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2714",
			                               "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/pulls/2714",
			                               "diff_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2714.diff"
			                            },
			                            "state" : "open",
			                            "body" : "Add a bunch more common forms that I've seen in the searches - also\r\nsupports a couple of forms that should've been supported before.\r\n\r\nThings like `What day will it be in 120 days?`, `What time was it 3 hours ago?` etc...\r\n\r\n---\r\nIA Page: https://duck.co/ia/view/date_math",
			                            "created_at" : "2016-03-07T18:44:59Z",
			                            "assignee" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/mintsoft/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/mintsoft/orgs",
			                               "gists_url" : "https://api.github.com/users/mintsoft/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/mintsoft/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/mintsoft/following{/other_user}",
			                               "url" : "https://api.github.com/users/mintsoft",
			                               "id" : 978048,
			                               "starred_url" : "https://api.github.com/users/mintsoft/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/978048?v=3",
			                               "repos_url" : "https://api.github.com/users/mintsoft/repos",
			                               "login" : "mintsoft",
			                               "html_url" : "https://github.com/mintsoft",
			                               "events_url" : "https://api.github.com/users/mintsoft/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/mintsoft/received_events",
			                               "type" : "User"
			                            },
			                            "user" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/GuiltyDolphin/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/GuiltyDolphin/orgs",
			                               "gists_url" : "https://api.github.com/users/GuiltyDolphin/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/GuiltyDolphin/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/GuiltyDolphin/following{/other_user}",
			                               "url" : "https://api.github.com/users/GuiltyDolphin",
			                               "id" : 8598426,
			                               "starred_url" : "https://api.github.com/users/GuiltyDolphin/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/8598426?v=3",
			                               "repos_url" : "https://api.github.com/users/GuiltyDolphin/repos",
			                               "login" : "GuiltyDolphin",
			                               "html_url" : "https://github.com/GuiltyDolphin",
			                               "events_url" : "https://api.github.com/users/GuiltyDolphin/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/GuiltyDolphin/received_events",
			                               "type" : "User"
			                            },
			                            "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2714",
			                            "id" : 139058174,
			                            "labels" : [
			                               {
			                                  "color" : "d7e102",
			                                  "name" : "Improvement",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/Improvement"
			                               },
			                               {
			                                  "color" : "f7c6c7",
			                                  "name" : "Triggering",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/Triggering"
			                               }
			                            ],
			                            "locked" : false,
			                            "repository_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies",
			                            "updated_at" : "2016-03-07T21:37:21Z",
			                            "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2714",
			                            "milestone" : null,
			                            "events_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2714/events",
			                            "title" : "DateMath: Expand Triggers"
			                         },
			"isa_pull_request"        : "1"
		},
		{
			"id"                      : "5526",
			"github_id"               : "139019656",
			"github_repo_id"          : "3",
			"github_user_id"          : "4379",
			"number"                  : "2713",
			"comments"                : "2",
			"title"                   : "Update a bunch of tab-answer names",
			"body"                    : "I for one ***love*** the answer tabs!\r \r Who doesn't want to have a choice of Instant Answers?:\r \r ![screenshot from 2016-03-07 16 03 51](https://cloud.githubusercontent.com/assets/8598426/13574934/4253f82c-e47e-11e5-9bb2-1eaa8aecefde.png)\r \r Unfortunately many of the Goodies were just using the `Answer` tab name, and some even had weird non-standard names!\r \r \r @moollaza I've updated the tab names as best I could, but I have a couple of requests:\r \r 1. We add a `Date & Time` category: We have *many* Instant Answers that would benefit from this (`Zodiac`, `CalendarToday`, `LeapYear` etc...)\r \r 2. We add a `Web` or `Net` category: Goodies such as `URLEncode`, `URLDecode`, and others would benefit from this!\r \r 3. We add a `Fun & Games` category - it doesn't feel right putting things into `Games` a lot of the time - for instance `MagicEightBall` - but I think `Fun & Games` is a pretty good catch-all. (There is a `Words & games` category but I'm not sure what that is *supposed* to apply to? Board games? - I much prefer `Fun & Games`).\r \r 4. We add an `Easter Eggs` category - we have quite a few of these! (Also, this would tell the person that yes, they have discovered an Easter Egg!)\r \r 5. We add a `Random` category for all the Instant Answers that are generating random stuff (there's quite a few)!\r \r 6. Either we add an `Engineering` category, or rename `Science` to `Science & Engineering` - there's a few (such as `ResistorColors`) for which this would make *more* sense.\r \r 7. We add a `Language` category for anything that deals with language and/or translations (such as `PigLatin`).\r \r 8. Sort of a design preference - rather than having lowercase as in `Food & drinks`, we always use uppercase `Food & Drinks` - I think it looks better.\r \r Note: I'm basing all the *allowed* categories on what is stated in the docs, so the suggestion is we *add* these to the docs (as well as IAs).\r \r /cc @duckduckgo/community-leaders @talsraviv ",
			"state"                   : "closed",
			"created_at"              : "2016-03-07 16:14:52+00",
			"updated_at"              : "2016-03-07 20:14:15+00",
			"closed_at"               : "2016-03-07 20:14:15+00",
			"github_user_id_assignee" : "2344",
			"created"                 : "2016-03-07 21:47:42+00",
			"updated"                 : "2016-03-07 21:47:42+00",
			"gh_data"                 : {
			                            "closed_at" : "2016-03-07T20:14:15Z",
			                            "number" : 2713,
			                            "comments_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2713/comments",
			                            "labels_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2713/labels{/name}",
			                            "comments" : 2,
			                            "pull_request" : {
			                               "patch_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2713.patch",
			                               "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2713",
			                               "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/pulls/2713",
			                               "diff_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2713.diff"
			                            },
			                            "state" : "closed",
			                            "body" : "I for one ***love*** the answer tabs!\r\n\r\nWho doesn't want to have a choice of Instant Answers?:\r\n\r\n![screenshot from 2016-03-07 16 03 51](https://cloud.githubusercontent.com/assets/8598426/13574934/4253f82c-e47e-11e5-9bb2-1eaa8aecefde.png)\r\n\r\nUnfortunately many of the Goodies were just using the `Answer` tab name, and some even had weird non-standard names!\r\n\r\n\r\n@moollaza I've updated the tab names as best I could, but I have a couple of requests:\r\n\r\n1. We add a `Date & Time` category: We have *many* Instant Answers that would benefit from this (`Zodiac`, `CalendarToday`, `LeapYear` etc...)\r\n\r\n2. We add a `Web` or `Net` category: Goodies such as `URLEncode`, `URLDecode`, and others would benefit from this!\r\n\r\n3. We add a `Fun & Games` category - it doesn't feel right putting things into `Games` a lot of the time - for instance `MagicEightBall` - but I think `Fun & Games` is a pretty good catch-all. (There is a `Words & games` category but I'm not sure what that is *supposed* to apply to? Board games? - I much prefer `Fun & Games`).\r\n\r\n4. We add an `Easter Eggs` category - we have quite a few of these! (Also, this would tell the person that yes, they have discovered an Easter Egg!)\r\n\r\n5. We add a `Random` category for all the Instant Answers that are generating random stuff (there's quite a few)!\r\n\r\n6. Either we add an `Engineering` category, or rename `Science` to `Science & Engineering` - there's a few (such as `ResistorColors`) for which this would make *more* sense.\r\n\r\n7. We add a `Language` category for anything that deals with language and/or translations (such as `PigLatin`).\r\n\r\n8. Sort of a design preference - rather than having lowercase as in `Food & drinks`, we always use uppercase `Food & Drinks` - I think it looks better.\r\n\r\nNote: I'm basing all the *allowed* categories on what is stated in the docs, so the suggestion is we *add* these to the docs (as well as IAs).\r\n\r\n/cc @duckduckgo/community-leaders @talsraviv ",
			                            "created_at" : "2016-03-07T16:14:52Z",
			                            "assignee" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/moollaza/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/moollaza/orgs",
			                               "gists_url" : "https://api.github.com/users/moollaza/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/moollaza/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/moollaza/following{/other_user}",
			                               "url" : "https://api.github.com/users/moollaza",
			                               "id" : 873785,
			                               "starred_url" : "https://api.github.com/users/moollaza/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/873785?v=3",
			                               "repos_url" : "https://api.github.com/users/moollaza/repos",
			                               "login" : "moollaza",
			                               "html_url" : "https://github.com/moollaza",
			                               "events_url" : "https://api.github.com/users/moollaza/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/moollaza/received_events",
			                               "type" : "User"
			                            },
			                            "user" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/GuiltyDolphin/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/GuiltyDolphin/orgs",
			                               "gists_url" : "https://api.github.com/users/GuiltyDolphin/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/GuiltyDolphin/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/GuiltyDolphin/following{/other_user}",
			                               "url" : "https://api.github.com/users/GuiltyDolphin",
			                               "id" : 8598426,
			                               "starred_url" : "https://api.github.com/users/GuiltyDolphin/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/8598426?v=3",
			                               "repos_url" : "https://api.github.com/users/GuiltyDolphin/repos",
			                               "login" : "GuiltyDolphin",
			                               "html_url" : "https://github.com/GuiltyDolphin",
			                               "events_url" : "https://api.github.com/users/GuiltyDolphin/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/GuiltyDolphin/received_events",
			                               "type" : "User"
			                            },
			                            "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2713",
			                            "id" : 139019656,
			                            "labels" : [
			                               {
			                                  "color" : "d7e102",
			                                  "name" : "Improvement",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/Improvement"
			                               },
			                               {
			                                  "color" : "bfe5bf",
			                                  "name" : "Needs Community Review",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/Needs%20Community%20Review"
			                               },
			                               {
			                                  "color" : "fbca04",
			                                  "name" : "On Hold",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/On%20Hold"
			                               },
			                               {
			                                  "color" : "e11d21",
			                                  "name" : "Staff Attention Requested",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/Staff%20Attention%20Requested"
			                               },
			                               {
			                                  "color" : "fbca04",
			                                  "name" : "Work In Progress",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/Work%20In%20Progress"
			                               }
			                            ],
			                            "locked" : false,
			                            "repository_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies",
			                            "updated_at" : "2016-03-07T20:14:15Z",
			                            "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2713",
			                            "milestone" : null,
			                            "events_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2713/events",
			                            "title" : "Update a bunch of tab-answer names"
			                         },
			"isa_pull_request"        : "1"
		},
		{
			"id"                      : "5520",
			"github_id"               : "138888508",
			"github_repo_id"          : "3",
			"github_user_id"          : "4647",
			"number"                  : "2711",
			"comments"                : "1",
			"title"                   : "New Stardate Goodie",
			"body"                    : "This is a basic version that returns the current stardate.\r Suggestions and improvements are welcome! :smile: \r IA Page: https://duck.co/ia/view/stardate",
			"state"                   : "open",
			"created_at"              : "2016-03-07 05:06:22+00",
			"updated_at"              : "2016-03-07 12:54:46+00",
			"github_user_id_assignee" : "4379",
			"created"                 : "2016-03-07 05:47:28+00",
			"updated"                 : "2016-03-07 13:47:35+00",
			"gh_data"                 : {
			                            "closed_at" : null,
			                            "number" : 2711,
			                            "comments_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2711/comments",
			                            "labels_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2711/labels{/name}",
			                            "comments" : 1,
			                            "pull_request" : {
			                               "patch_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2711.patch",
			                               "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2711",
			                               "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/pulls/2711",
			                               "diff_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2711.diff"
			                            },
			                            "state" : "open",
			                            "body" : "This is a basic version that returns the current stardate.\r\nSuggestions and improvements are welcome! :smile: \r\nIA Page: https://duck.co/ia/view/stardate",
			                            "created_at" : "2016-03-07T05:06:22Z",
			                            "assignee" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/GuiltyDolphin/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/GuiltyDolphin/orgs",
			                               "gists_url" : "https://api.github.com/users/GuiltyDolphin/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/GuiltyDolphin/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/GuiltyDolphin/following{/other_user}",
			                               "url" : "https://api.github.com/users/GuiltyDolphin",
			                               "id" : 8598426,
			                               "starred_url" : "https://api.github.com/users/GuiltyDolphin/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/8598426?v=3",
			                               "repos_url" : "https://api.github.com/users/GuiltyDolphin/repos",
			                               "login" : "GuiltyDolphin",
			                               "html_url" : "https://github.com/GuiltyDolphin",
			                               "events_url" : "https://api.github.com/users/GuiltyDolphin/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/GuiltyDolphin/received_events",
			                               "type" : "User"
			                            },
			                            "user" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/swapagarwal/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/swapagarwal/orgs",
			                               "gists_url" : "https://api.github.com/users/swapagarwal/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/swapagarwal/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/swapagarwal/following{/other_user}",
			                               "url" : "https://api.github.com/users/swapagarwal",
			                               "id" : 2833845,
			                               "starred_url" : "https://api.github.com/users/swapagarwal/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/2833845?v=3",
			                               "repos_url" : "https://api.github.com/users/swapagarwal/repos",
			                               "login" : "swapagarwal",
			                               "html_url" : "https://github.com/swapagarwal",
			                               "events_url" : "https://api.github.com/users/swapagarwal/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/swapagarwal/received_events",
			                               "type" : "User"
			                            },
			                            "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2711",
			                            "id" : 138888508,
			                            "labels" : [
			                               {
			                                  "color" : "02d7e1",
			                                  "name" : "New Instant Answer",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/New%20Instant%20Answer"
			                               }
			                            ],
			                            "locked" : false,
			                            "repository_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies",
			                            "updated_at" : "2016-03-07T12:54:46Z",
			                            "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2711",
			                            "milestone" : null,
			                            "events_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2711/events",
			                            "title" : "New Stardate Goodie"
			                         },
			"isa_pull_request"        : "1"
		},
		{
			"id"                      : "5516",
			"github_id"               : "138784051",
			"github_repo_id"          : "3",
			"github_user_id"          : "4379",
			"number"                  : "2708",
			"comments"                : "8",
			"title"                   : "GibberishGenerator: Fix failing tests",
			"body"                    : "@mintsoft Fixes #2707 \r \r ---\r IA Page: https://duck.co/ia/view/gibberish_generator",
			"state"                   : "closed",
			"created_at"              : "2016-03-06 11:28:20+00",
			"updated_at"              : "2016-03-08 16:09:37+00",
			"closed_at"               : "2016-03-07 21:07:46+00",
			"github_user_id_assignee" : "2397",
			"created"                 : "2016-03-06 13:47:27+00",
			"updated"                 : "2016-03-08 17:47:48+00",
			"gh_data"                 : {
			                            "closed_at" : "2016-03-07T21:07:46Z",
			                            "number" : 2708,
			                            "comments_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2708/comments",
			                            "labels_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2708/labels{/name}",
			                            "comments" : 8,
			                            "pull_request" : {
			                               "patch_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2708.patch",
			                               "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2708",
			                               "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/pulls/2708",
			                               "diff_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2708.diff"
			                            },
			                            "state" : "closed",
			                            "body" : "@mintsoft Fixes #2707 \r\n\r\n---\r\nIA Page: https://duck.co/ia/view/gibberish_generator",
			                            "created_at" : "2016-03-06T11:28:20Z",
			                            "assignee" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/mintsoft/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/mintsoft/orgs",
			                               "gists_url" : "https://api.github.com/users/mintsoft/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/mintsoft/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/mintsoft/following{/other_user}",
			                               "url" : "https://api.github.com/users/mintsoft",
			                               "id" : 978048,
			                               "starred_url" : "https://api.github.com/users/mintsoft/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/978048?v=3",
			                               "repos_url" : "https://api.github.com/users/mintsoft/repos",
			                               "login" : "mintsoft",
			                               "html_url" : "https://github.com/mintsoft",
			                               "events_url" : "https://api.github.com/users/mintsoft/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/mintsoft/received_events",
			                               "type" : "User"
			                            },
			                            "user" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/GuiltyDolphin/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/GuiltyDolphin/orgs",
			                               "gists_url" : "https://api.github.com/users/GuiltyDolphin/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/GuiltyDolphin/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/GuiltyDolphin/following{/other_user}",
			                               "url" : "https://api.github.com/users/GuiltyDolphin",
			                               "id" : 8598426,
			                               "starred_url" : "https://api.github.com/users/GuiltyDolphin/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/8598426?v=3",
			                               "repos_url" : "https://api.github.com/users/GuiltyDolphin/repos",
			                               "login" : "GuiltyDolphin",
			                               "html_url" : "https://github.com/GuiltyDolphin",
			                               "events_url" : "https://api.github.com/users/GuiltyDolphin/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/GuiltyDolphin/received_events",
			                               "type" : "User"
			                            },
			                            "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2708",
			                            "id" : 138784051,
			                            "labels" : [
			                               {
			                                  "color" : "d7e102",
			                                  "name" : "Improvement",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/Improvement"
			                               }
			                            ],
			                            "locked" : false,
			                            "repository_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies",
			                            "updated_at" : "2016-03-08T16:09:37Z",
			                            "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2708",
			                            "milestone" : null,
			                            "events_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2708/events",
			                            "title" : "GibberishGenerator: Fix failing tests"
			                         },
			"isa_pull_request"        : "1"
		},
		{
			
			"id"                      : "5517",
			"github_id"               : "138780671",
			"github_repo_id"          : "3",
			"github_user_id"          : "2397",
			"number"                  : "2707",
			"comments"                : "1",
			"title"                   : "GibberishGenerator: Tests randomly fail",
			"body"                    : "I've just had a PR go boom with this randomly failing, if the test are executed like 20 times, then it'll fail 1-2/20:\r \r ![randomtests](https://cloud.githubusercontent.com/assets/978048/13553641/c9eaa6ca-e387-11e5-95cf-8c9d073835ee.png)\r ",
			"state"                   : "closed",
			"created_at"              : "2016-03-06 10:40:15+00",
			"updated_at"              : "2016-03-07 21:07:46+00",
			"closed_at"               : "2016-03-07 21:07:46+00",
			"github_user_id_assignee" : "4379",
			"created"                 : "2016-03-06 13:47:27+00",
			"updated"                 : "2016-03-07 21:47:42+00",
			"gh_data"                 : {
			                            "closed_at" : "2016-03-07T21:07:46Z",
			                            "number" : 2707,
			                            "comments_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2707/comments",
			                            "labels_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2707/labels{/name}",
			                            "comments" : 1,
			                            "state" : "closed",
			                            "body" : "I've just had a PR go boom with this randomly failing, if the test are executed like 20 times, then it'll fail 1-2/20:\r\n\r\n![randomtests](https://cloud.githubusercontent.com/assets/978048/13553641/c9eaa6ca-e387-11e5-95cf-8c9d073835ee.png)\r\n",
			                            "created_at" : "2016-03-06T10:40:15Z",
			                            "assignee" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/GuiltyDolphin/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/GuiltyDolphin/orgs",
			                               "gists_url" : "https://api.github.com/users/GuiltyDolphin/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/GuiltyDolphin/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/GuiltyDolphin/following{/other_user}",
			                               "url" : "https://api.github.com/users/GuiltyDolphin",
			                               "id" : 8598426,
			                               "starred_url" : "https://api.github.com/users/GuiltyDolphin/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/8598426?v=3",
			                               "repos_url" : "https://api.github.com/users/GuiltyDolphin/repos",
			                               "login" : "GuiltyDolphin",
			                               "html_url" : "https://github.com/GuiltyDolphin",
			                               "events_url" : "https://api.github.com/users/GuiltyDolphin/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/GuiltyDolphin/received_events",
			                               "type" : "User"
			                            },
			                            "user" : {
			                               "gravatar_id" : "",
			                               "subscriptions_url" : "https://api.github.com/users/mintsoft/subscriptions",
			                               "organizations_url" : "https://api.github.com/users/mintsoft/orgs",
			                               "gists_url" : "https://api.github.com/users/mintsoft/gists{/gist_id}",
			                               "followers_url" : "https://api.github.com/users/mintsoft/followers",
			                               "site_admin" : false,
			                               "following_url" : "https://api.github.com/users/mintsoft/following{/other_user}",
			                               "url" : "https://api.github.com/users/mintsoft",
			                               "id" : 978048,
			                               "starred_url" : "https://api.github.com/users/mintsoft/starred{/owner}{/repo}",
			                               "avatar_url" : "https://avatars.githubusercontent.com/u/978048?v=3",
			                               "repos_url" : "https://api.github.com/users/mintsoft/repos",
			                               "login" : "mintsoft",
			                               "html_url" : "https://github.com/mintsoft",
			                               "events_url" : "https://api.github.com/users/mintsoft/events{/privacy}",
			                               "received_events_url" : "https://api.github.com/users/mintsoft/received_events",
			                               "type" : "User"
			                            },
			                            "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2707",
			                            "id" : 138780671,
			                            "labels" : [
			                               {
			                                  "color" : "e11d21",
			                                  "name" : "Bug",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/Bug"
			                               },
			                               {
			                                  "color" : "eb6420",
			                                  "name" : "Priority: High",
			                                  "url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/labels/Priority:%20High"
			                               }
			                            ],
			                            "locked" : false,
			                            "repository_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies",
			                            "updated_at" : "2016-03-07T21:07:46Z",
			                            "html_url" : "https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2707",
			                            "milestone" : null,
			                            "events_url" : "https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/issues/2707/events",
			                            "title" : "GibberishGenerator: Tests randomly fail"
			                         },
			"isa_pull_request"        : "0"
		}
	]
};


